name: HoverWorth
version: '2.0.1'
main: com.jolly.hoverworth.HoverWorth
api-version: '1.21'
authors: [ Jolly, siberanka ]
folia-supported: true
depend: [packetevents]
commands:
  hwreload:
    usage: /hwreload
    permission: hoverworth.reload

permissions:
  hoverworth.reload:
    default: op
